name: Publish To NuGet

on:
  workflow_dispatch:

jobs:
  publish-nuget:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
        with:
          fetch-depth: 1
      - name: Init Nuget
        run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      - name: Pack
        run: |
          dotnet pack -c Release
          $nupkgFiles = Get-ChildItem -Path bin\Release\ -Filter *.nupkg
          cd src
          dotnet nuget push $nupkgFiles[0].FullName --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
